import { FormData } from "@/app/auth";
import React, { createContext, useState, useContext } from "react";

const defaultNoop = () => { };

const FormDataContext = createContext<{
  formData: FormData;
  setFormData: React.Dispatch<React.SetStateAction<FormData>>;
  formData1: any;
  setFormData1: React.Dispatch<React.SetStateAction<any>>;
}>({
  formData: {
    compcode: null,
    Emgy_No: null,
    Emgy_Mob_No: null,
    empty: null,
    EMPCODE: null,
    HR_REASON: null,
    MACHINE_NAME: null,
    PAN_VERIFICATION: null,
    AADHAR_VERIFICATION: null,
    PASSPORT_VERIFICATION: null,
    DRIVING_VERIFICATION: null,
    STATE1: null,
    CITY1: null,
    RELIGION1: null,
    LOC_CODE1: null,
    APPLICATION_DATE1: null,
    DOB1: null,
    DOM1: null,
    employeename1: null,
    employeename2: null,
    employeename3: null,
    employeename4: null,
    TRAN_ID: null,
    NAME: null,
    MOB_NO: null,
    WHATSAPP_NO: null,
    ADDRESS: null,
    PINCODE: null,
    STATE: null,
    CITY: null,
    HIGH_QUAL: null,
    PASSING_PER: null,
    FATHERS_NAME: null,
    GENDER: null,
    MOTHERS_NAME: null,
    EXP_IN_YEAR: null,
    CURRENT_CTC: null,
    LOC_CODE: null,
    DESIGNATION: null,
    EMAIL: null,
    AADHAR_NO: null,
    DOB: null,
    DOM: null,
    RELIGION: null,
    APPLICATION_DATE: null,
    INT_STATUS: null,
    INTR1DATE: null,
    INTR1TIME: null,
    INTR2TIME: null,
    INTR2DATE: null,
    INTR1BY: null,
    INTR2BY: null,
    INTR3BY: null,
    INTR4BY: null,
    INTR4TIME: null,
    INTR3TIME: null,
    INTR3DATE: null,
    INTR4DATE: null,
    REJECTION_REMARK: null,
    INTR1STATUS: null,
    INTR2STATUS: null,
    INTR3STATUS: null,
    INTR4STATUS: null,
    SKILLS: null,
    SOURCE_OF_REG: null,
    SUB_SOURCE: null,
    INTR1REMARK: null,
    INTR1RATING: null,
    INTR1SALARY: null,
    INTR2REMARK: null,
    INTR2RATING: null,
    INTR2SALARY: null,
    INTR4REMARK: null,
    INTR4RATING: null,
    INTR4SALARY: null,
    INTR3REMARK: null,
    INTR3RATING: null,
    INTR3SALARY: null,
    UNIQUE_ID: null,
    TITLE: null,
    EMPLOYEEDESIGNATION: null,
    CURRENTJOINDATE: null,


    ACCOUNT_TYPE: null,
    ADHARNO: null,
    ADUSER_NAME: null,
    ALTERNET_MAIL: null,
    ANNUAL_CTC: null,
    APPLICATION_ID: null,
    APPROVED_AUTHO: null,
    AUTOMAILER: null,
    AX_BAL: null,
    AX_EMP_CODE: null,
    Acnt_Loc: null,
    Android_ID: null,
    App_Attendance: null,
    App_Leave: null,
    App_Mispunch: null,
    BANKACCOUNTNO: null,
    BANKNAME: null,
    BASICQUALIFICATION: null,
    BIOMETRIC_ID: null,
    BLOODGROUP: null,
    BONUS_AMOUNT: null,
    BRANCH: null,
    CCITY: null,
    CHILDREN_DETAIL: null,
    CNATIONALITY: null,
    COMP_NAME: null,
    CORPORATEMAILID: null,
    CPINCODE: null,
    CREATED_BY: null,
    CREATED_ON: null,
    CSTATE: null,
    CURRENTADDRESS1: null,
    CURRENTADDRESS2: null,
    // CURRENTJOINDATE: null,
    Cumulative_Relaxation: null,
    DIVISION: null,
    // DOB: null,
    // DOM: null,
    DRIVINGLIC_ISSUEDATE: null,
    DRIVINGLIC_ISSUEPALACE: null,
    EMERGENCYNAME: null,
    EMERGENCYNO: null,
    EMPCODE: null,
    EMPDEPENDENT: null,
    EMPFIRSTNAME: null,
    EMPHEIGHT: null,
    EMPLASTNAME: null,
    // EMPLOYEEDESIGNATION: null,
    EMPLOYEETYPE: null,
    EMPREFERENCENAME: null,
    EMPWEIGHT: null,
    EMP_SHIFT: null,
    EMP_STATUS: null,
    ESINO: null,
    ESI_AMOUNT: null,
    ESI_DEDUCTION: null,
    ESI_Date: null,
    EXT_NO: null,
    EmpType: null,
    Emp_Ac_Name: null,
    ExitInterview_Done: null,
    Exp_Date: null,
    Export_Type: null,
    FATHERCONTACTNO: null,
    FATHERNAME: null,
    FATHEROCCUPATION: null,
    FCM_TockenId: null,
    Father_Mob: null,
    // GENDER: null,
    GRADE: null,
    IEMI: null,
    ISALLERGIES: null,
    ISMEDICALATTENTION: null,
    ISPAYROLL: null,
    ISSERIOUSILLNESS: null,
    ISTIMEVALIDATION: null,
    InBudget: null,
    Induction_Done: null,
    Interview_Date: null,
    IsMSPN: null,
    IsRW: null,
    Is_Profile_Filled: null,
    JOINING_TYPE: null,
    LANDLINENO: null,
    LANGUAGE_DETAIL: null,
    LASTMODI_BY: null,
    LASTMODI_ON: null,
    LASTWOR_DATE: null,
    LEVEL: null,
    LOCATION: null,
    LWF: null,
    LWFNO: null,
    Ledger_Code: null,
    Loc_Code: null,
    MARITALSTATUS: null,
    MOBILENO: null,
    MOBILE_NO: null,
    MONTHLY_CTC: null,
    MOTHERCONTACTNO: null,
    MOTHERNAME: null,
    MSPIN: null,
    MSPN_DTL: null,
    MSPN_Id: null,
    Mother_Mob: null,
    NOMINEE_DETAIL: null,
    NOTICEPERIOD: null,
    ORGANISATIONNAME: null,
    PANNO: null,
    PASSEXPIRYDATE: null,
    PASSPORTNO: null,
    PASSPORT_EXPDATE: null,
    PAYCYCLEDURATION: null,
    PAYMENTMODE: null,
    PAY_CODE: null,
    PCITY: null,
    PERMANENTADDRESS1: null,
    PERMANENTADDRESS2: null,
    PF: null,
    PFNO: null,
    PFSALARY_LIMIT: null,
    PFTRUST_NO: null,
    PF_DEDUCTION: null,
    PF_Date: null,
    PPINCODE: null,
    PRECOMPCITY: null,
    PRECOMPCONTACTNO: null,
    PREDESIGNATION: null,
    PREENDDATE: null,
    PREJOININGDATE: null,
    PREVIOUSCOMPANYNAME: null,
    PROBATIONLEAVES: null,
    PROBATIONPERIOD: null,
    PROFESSIONALQUALIFICATION: null,
    PROPOSEDRETIRE_DATE: null,
    PSTATE: null,
    P_NATIONALITY: null,
    Prob_period: null,
    Punch_Type: null,
    REFERENCEDESIGNATION: null,
    REGION: null,
    RELCODE: null,
    RELEVE_STATUS: null,
    RESIGN_APPR: null,
    ROLE: null,
    Rec_Date: null,
    Relaxation_Type: null,
    Reporting_1: null,
    Reporting_2: null,
    Reporting_3: null,
    SBU_FUNCTION: null,
    SECTION: null,
    SIBLINGCONTACTNO: null,
    SIBLINGNAME: null,
    // SKILLS: null,
    SPOUSECONTACTNO: null,
    SPOUSEGENDER: null,
    SPOUSENAME: null,
    SRNO: null,
    SUPERVISOR: null,
    SUPERVISORID: null,
    Sal_Hold: null,
    Sal_Region: null,
    ServerId: null,
    ShiftIn_Relaxation: null,
    ShiftOut_Relaxation: null,
    Spl_Rem: null,
    Spouse_Mob: null,
    TCS_Rate: null,
    // TITLE: null,
    Tocken_Id: null,
    Token: null,
    UAN_No: null,
    UID_NO: null,
    UNIT: null,
    USR_NAME: null,
    WEEKLYOFF: null,
    columndoc_type: null,
    driving_licence: null,
    ein: null,
    empcode2: null,
    empcode3: null,
    empcode4: null,
    esinumber: null,
    esiper: null,
    ifsc_code: null,
    landline_no: null,
    mApprove: null,
    mAssetScan: null,
    mAttendanceLog: null,
    mCalender: null,
    mDeviceLog: null,
    mGeoFenceSetting: null,
    mLeave: null,
    mLiveLocation: null,
    mLocationLog: null,
    mMispunch: null,
    mPunch: null,
    mSuggestions: null,
    mToDoList: null,
    mTrackingReport: null,
    mUpdateIMEI: null,
    mobile_limit: null,
    multi_loc: null,
    pfnumber: null,
    pfper: null,
    pre_Exp: null,
    pro_tax: null,
    uidno: null,
    CrtiriaVald: null,
    //new add by manish
    RescheduleRemark: null,
    RescheduleDate: null,
    RescheduleTime: null,

    EmpEdu: [],
    EmpLang: [],
    EmpItSkill: [],
    EmpExperience: [],
    AssetIssue: [],
    EmpFamily: [],
    EmpNominee: [],
    References: [],

    imageFiles: [],
    ImgSourseArray: [],
    ImgSourseArray1: [],

    imageSrc1: null,
    imageSrc2: null,
    imageSrc3: null,
    imageSrc4: null,
    imageSrc5: null,
    imageSrc6: null,
    imageFile1: null,
    imageFile2: null,
    imageFile3: null,
    imageFile4: null,
    imageFile5: null,
    imageFile6: null,

    images: [],
    path: null,
    File_Name: null,



  },
  setFormData: defaultNoop,
  formData1: {} as any,
  setFormData1: defaultNoop,
});

export const useFormData = () => {
  return useContext(FormDataContext);
};
interface FormDataProviderProps {
  children: React.ReactNode;
}

export const FormDataProvider: React.FC<FormDataProviderProps> = ({
  children,
}) => {
  const existing = useContext(FormDataContext);
  if (existing && existing.setFormData !== defaultNoop) {
    return <>{children}</>;
  }

  const [formData, setFormData] = useState<FormData>(
    {
      Emgy_No: null,
      compcode: null,
      Emgy_Mob_No: null,
      empty: null,
      EMPCODE: null,
      HR_REASON: null,
      MACHINE_NAME: null,
      PAN_VERIFICATION: null,
      AADHAR_VERIFICATION: null,
      PASSPORT_VERIFICATION: null,
      DRIVING_VERIFICATION: null,
      STATE1: null,
      CITY1: null,
      RELIGION1: null,
      LOC_CODE1: null,
      APPLICATION_DATE1: null,
      DOB1: null,
      DOM1: null,
      employeename1: null,
      employeename2: null,
      employeename3: null,
      employeename4: null,
      TRAN_ID: null,
      NAME: null,
      MOB_NO: null,
      WHATSAPP_NO: null,
      ADDRESS: null,
      PINCODE: null,
      STATE: null,
      CITY: null,
      HIGH_QUAL: null,
      PASSING_PER: null,
      FATHERS_NAME: null,
      GENDER: null,
      MOTHERS_NAME: null,
      EXP_IN_YEAR: null,
      CURRENT_CTC: null,
      LOC_CODE: null,
      DESIGNATION: null,
      EMAIL: null,
      AADHAR_NO: null,
      DOB: null,
      DOM: null,
      RELIGION: null,
      APPLICATION_DATE: null,
      INT_STATUS: null,
      INTR1DATE: null,
      INTR1TIME: null,
      INTR2TIME: null,
      INTR2DATE: null,
      INTR1BY: null,
      INTR2BY: null,
      INTR3BY: null,
      INTR4BY: null,
      INTR4TIME: null,
      INTR3TIME: null,
      INTR3DATE: null,
      INTR4DATE: null,
      REJECTION_REMARK: null,
      INTR1STATUS: null,
      INTR2STATUS: null,
      INTR3STATUS: null,
      INTR4STATUS: null,
      SKILLS: null,
      SOURCE_OF_REG: null,
      SUB_SOURCE: null,
      INTR1REMARK: null,
      INTR1RATING: null,
      INTR1SALARY: null,
      INTR2REMARK: null,
      INTR2RATING: null,
      INTR2SALARY: null,
      INTR4REMARK: null,
      INTR4RATING: null,
      INTR4SALARY: null,
      INTR3REMARK: null,
      INTR3RATING: null,
      INTR3SALARY: null,
      UNIQUE_ID: null,
      TITLE: null,
      EMPLOYEEDESIGNATION: null,
      CURRENTJOINDATE: null,


      ACCOUNT_TYPE: null,
      ADHARNO: null,
      ADUSER_NAME: null,
      ALTERNET_MAIL: null,
      ANNUAL_CTC: null,
      APPLICATION_ID: null,
      APPROVED_AUTHO: null,
      AUTOMAILER: null,
      AX_BAL: null,
      AX_EMP_CODE: null,
      Acnt_Loc: null,
      Android_ID: null,
      App_Attendance: null,
      App_Leave: null,
      App_Mispunch: null,
      BANKACCOUNTNO: null,
      BANKNAME: null,
      BASICQUALIFICATION: null,
      BIOMETRIC_ID: null,
      BLOODGROUP: null,
      BONUS_AMOUNT: null,
      BRANCH: null,
      CCITY: null,
      CHILDREN_DETAIL: null,
      CNATIONALITY: null,
      COMP_NAME: null,
      CORPORATEMAILID: null,
      CPINCODE: null,
      CREATED_BY: null,
      CREATED_ON: null,
      CSTATE: null,
      CURRENTADDRESS1: null,
      CURRENTADDRESS2: null,
      // CURRENTJOINDATE: null,
      Cumulative_Relaxation: null,
      DIVISION: null,
      // DOB: null,
      // DOM: null,
      DRIVINGLIC_ISSUEDATE: null,
      DRIVINGLIC_ISSUEPALACE: null,
      EMERGENCYNAME: null,
      EMERGENCYNO: null,
      EMPCODE: null,
      EMPDEPENDENT: null,
      EMPFIRSTNAME: null,
      EMPHEIGHT: null,
      EMPLASTNAME: null,
      // EMPLOYEEDESIGNATION: null,
      EMPLOYEETYPE: null,
      EMPREFERENCENAME: null,
      EMPWEIGHT: null,
      EMP_SHIFT: null,
      EMP_STATUS: null,
      ESINO: null,
      ESI_AMOUNT: null,
      ESI_DEDUCTION: null,
      ESI_Date: null,
      EXT_NO: null,
      EmpType: null,
      Emp_Ac_Name: null,
      ExitInterview_Done: null,
      Exp_Date: null,
      Export_Type: null,
      FATHERCONTACTNO: null,
      FATHERNAME: null,
      FATHEROCCUPATION: null,
      FCM_TockenId: null,
      Father_Mob: null,
      // GENDER: null,
      GRADE: null,
      IEMI: null,
      ISALLERGIES: null,
      ISMEDICALATTENTION: null,
      ISPAYROLL: null,
      ISSERIOUSILLNESS: null,
      ISTIMEVALIDATION: null,
      InBudget: null,
      Induction_Done: null,
      Interview_Date: null,
      IsMSPN: null,
      IsRW: null,
      Is_Profile_Filled: null,
      JOINING_TYPE: null,
      LANDLINENO: null,
      LANGUAGE_DETAIL: null,
      LASTMODI_BY: null,
      LASTMODI_ON: null,
      LASTWOR_DATE: null,
      LEVEL: null,
      LOCATION: null,
      LWF: null,
      LWFNO: null,
      Ledger_Code: null,
      Loc_Code: null,
      MARITALSTATUS: null,
      MOBILENO: null,
      MOBILE_NO: null,
      MONTHLY_CTC: null,
      MOTHERCONTACTNO: null,
      MOTHERNAME: null,
      MSPIN: null,
      MSPN_DTL: null,
      MSPN_Id: null,
      Mother_Mob: null,
      NOMINEE_DETAIL: null,
      NOTICEPERIOD: null,
      ORGANISATIONNAME: null,
      PANNO: null,
      PASSEXPIRYDATE: null,
      PASSPORTNO: null,
      PASSPORT_EXPDATE: null,
      PAYCYCLEDURATION: null,
      PAYMENTMODE: null,
      PAY_CODE: null,
      PCITY: null,
      PERMANENTADDRESS1: null,
      PERMANENTADDRESS2: null,
      PF: null,
      PFNO: null,
      PFSALARY_LIMIT: null,
      PFTRUST_NO: null,
      PF_DEDUCTION: null,
      PF_Date: null,
      PPINCODE: null,
      PRECOMPCITY: null,
      PRECOMPCONTACTNO: null,
      PREDESIGNATION: null,
      PREENDDATE: null,
      PREJOININGDATE: null,
      PREVIOUSCOMPANYNAME: null,
      PROBATIONLEAVES: null,
      PROBATIONPERIOD: null,
      PROFESSIONALQUALIFICATION: null,
      PROPOSEDRETIRE_DATE: null,
      PSTATE: null,
      P_NATIONALITY: null,
      Prob_period: null,
      Punch_Type: null,
      REFERENCEDESIGNATION: null,
      REGION: null,
      RELCODE: null,
      RELEVE_STATUS: null,
      RESIGN_APPR: null,
      ROLE: null,
      Rec_Date: null,
      Relaxation_Type: null,
      Reporting_1: null,
      Reporting_2: null,
      Reporting_3: null,
      SBU_FUNCTION: null,
      SECTION: null,
      SIBLINGCONTACTNO: null,
      SIBLINGNAME: null,
      // SKILLS: null,
      SPOUSECONTACTNO: null,
      SPOUSEGENDER: null,
      SPOUSENAME: null,
      SRNO: null,
      SUPERVISOR: null,
      SUPERVISORID: null,
      Sal_Hold: null,
      Sal_Region: null,
      ServerId: null,
      ShiftIn_Relaxation: null,
      ShiftOut_Relaxation: null,
      Spl_Rem: null,
      Spouse_Mob: null,
      TCS_Rate: null,
      // TITLE: null,
      Tocken_Id: null,
      Token: null,
      UAN_No: null,
      UID_NO: null,
      UNIT: null,
      USR_NAME: null,
      WEEKLYOFF: null,
      columndoc_type: null,
      driving_licence: null,
      ein: null,
      empcode2: null,
      empcode3: null,
      empcode4: null,
      esinumber: null,
      esiper: null,
      ifsc_code: null,
      landline_no: null,
      mApprove: null,
      mAssetScan: null,
      mAttendanceLog: null,
      mCalender: null,
      mDeviceLog: null,
      mGeoFenceSetting: null,
      mLeave: null,
      mLiveLocation: null,
      mLocationLog: null,
      mMispunch: null,
      mPunch: null,
      mSuggestions: null,
      mToDoList: null,
      mTrackingReport: null,
      mUpdateIMEI: null,
      mobile_limit: null,
      multi_loc: null,
      pfnumber: null,
      pfper: null,
      pre_Exp: null,
      pro_tax: null,
      uidno: null,
      CrtiriaVald: null,

      RescheduleDate: null,
      RescheduleTime: null,

      EmpEdu: [],
      EmpLang: [],
      EmpItSkill: [],
      EmpExperience: [],
      AssetIssue: [],
      EmpFamily: [],
      imageFiles: [],
      References: [],
      EmpNominee: [],
      ImgSourseArray: [],
      ImgSourseArray1: [],

      imageSrc1: null,
      imageSrc2: null,
      imageSrc3: null,
      imageSrc4: null,
      imageSrc5: null,
      imageSrc6: null,
      imageFile1: null,
      imageFile2: null,
      imageFile3: null,
      imageFile4: null,
      imageFile5: null,
      imageFile6: null,

      images: [],
      path: null,
      File_Name: null,

    },
  );

  const [formData1, setFormData1] = useState<any>({});

  return (
    <FormDataContext.Provider
      value={{
        formData,
        setFormData,
        formData1,
        setFormData1,
      }}
    >
      {children}
    </FormDataContext.Provider>
  );
};

export default FormDataContext;
